services:
  ds:
    image: registry.digitalocean.com/carlosvillu/ds:latest
    ports:
      - '3002:8043'
    command: /bin/bash

  redis:
    image: redis/redis-stack-server:latest
    restart: always
    volumes:
      - redis_data:/data
    ports:
      - '6379:6379'
    networks:
      - net
volumes:
  redis_data:

networks:
  net:






