name: Client CI

on:
  push:
    branches: [ master, develop ]
    paths: 
      - 'packages/client/**'
      - '.github/workflows/client-ci.yml'
  pull_request:
    branches: [ master, develop ]
    paths: 
      - 'packages/client/**'
      - '.github/workflows/client-ci.yml'

jobs:
  test:
    name: Test & Build Client
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18, 20, 21]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Lint client
        run: npm run lint --workspace=@cervantes/client
        
      - name: Type check client
        run: npm run type-check --workspace=@cervantes/client
        
      - name: Test client
        run: npm run test --workspace=@cervantes/client
        
      - name: Build client
        run: npm run build --workspace=@cervantes/client
        
      - name: Upload coverage reports
        if: matrix.node-version == 21
        uses: codecov/codecov-action@v3
        with:
          file: ./packages/client/coverage/lcov.info
          flags: client
          name: client-coverage
          
  publish:
    name: Publish Package
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 21
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build client
        run: npm run build --workspace=@cervantes/client
        
      # TODO: Add semantic release or manual version bump logic
      # - name: Publish to NPM
      #   run: npm publish --workspace=@cervantes/client
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}